name: Artifacts

on:
  push:
    branches:
      - "master"

env:
  ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: action/upload-artifacts@v2
        with: 
          name: ${{ env.ARTIFACT_NAME }}
          path: .
