name: CI & CD Deploy

on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and test
      uses: actions/checkout@v2
      - run: python hello.py
